"""empty message

Revision ID: 2443f7b21005
Revises: 
Create Date: 2020-09-08 18:17:55.000710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2443f7b21005'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=12), nullable=True),
    sa.Column('last_name', sa.String(length=12), nullable=True),
    sa.Column('username', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_first_name'), 'employee', ['first_name'], unique=False)
    op.create_index(op.f('ix_employee_last_name'), 'employee', ['last_name'], unique=False)
    op.create_index(op.f('ix_employee_username'), 'employee', ['username'], unique=False)
    op.create_table('assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('classification', sa.String(length=10), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignment_classification'), 'assignment', ['classification'], unique=False)
    op.create_index(op.f('ix_assignment_day'), 'assignment', ['day'], unique=False)
    op.create_index(op.f('ix_assignment_month'), 'assignment', ['month'], unique=False)
    op.create_index(op.f('ix_assignment_year'), 'assignment', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assignment_year'), table_name='assignment')
    op.drop_index(op.f('ix_assignment_month'), table_name='assignment')
    op.drop_index(op.f('ix_assignment_day'), table_name='assignment')
    op.drop_index(op.f('ix_assignment_classification'), table_name='assignment')
    op.drop_table('assignment')
    op.drop_index(op.f('ix_employee_username'), table_name='employee')
    op.drop_index(op.f('ix_employee_last_name'), table_name='employee')
    op.drop_index(op.f('ix_employee_first_name'), table_name='employee')
    op.drop_table('employee')
    # ### end Alembic commands ###
